# See PEP 518: https://www.python.org/dev/peps/pep-0518/ for info on this file's structure.

[tool.pyflow]
name = ""
py_version = "3.7"
version = "0.1.0"

[tool.pyflow.scripts]

[tool.pyflow.dependencies]

[tool.pyflow.dev-dependencies]
bandit = "^1.6.2"
black = "^19.10.0b0"
flake8 = "^3.8.3"
flake8-docstrings = "^1.5.0"
hacking = "^3.1.0"
mypy = "^0.782.0"
pytest = "^5.4.3"
pytest-cov = "^2.10.0"
